# 1850
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Enkel Sample API

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yml

  geohash:
    Type: AWS::Serverless::Function
    Properties:
